[build]
command = "npm run cloudflare-build"
output_directory = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = ".vercel/output/functions"
[functions.[[path]]]
pattern = ".*"
function = "[[path]].func"

[site]
bucket = ".vercel/output/static"
include = ["_next/static/*"]
